"""Profiles, failure types, fixes and challenge presets for the ML Failure Lab."""

# Feature tuple: (name, dist, a, b, coef on standardized latent, unit, description)
#   dist: normal(mean, std) | lognormal(mu, sigma) | uniform(lo, hi) | binary(p, _) | poisson(lam, _)
CLASSIFICATION = {
    "credit_card_fraud": dict(
        title="Credit-card fraud",
        group="Fraud detection",
        target="is_fraud",
        base_rate=0.035,
        entity=("merchant_id", 120),
        ring=dict(size=5, effect=2.6, share=0.05),
        patterns=["Stolen card", "Unusual location", "Velocity fraud", "Merchant collusion"],
        features=[
            ("amount", "lognormal", 3.6, 0.9, 0.9, "USD", "Transaction amount"),
            ("distance_km", "lognormal", 2.0, 1.1, 0.8, "km", "Distance from home location"),
            ("velocity_1h", "poisson", 1.5, 0, 1.0, "count", "Card transactions in the last hour"),
            ("merchant_risk", "uniform", 0, 1, 0.6, "score", "Merchant category risk"),
            ("account_age_days", "lognormal", 6.0, 0.8, -0.5, "days", "Age of the card account"),
            ("foreign", "binary", 0.12, 0, 0.5, "flag", "Foreign transaction"),
            ("hour", "uniform", 0, 23, 0.1, "hour", "Hour of day"),
            ("device_new", "binary", 0.1, 0, 0.7, "flag", "First time this device is seen"),
        ],
        interaction=("amount", "distance_km", 1.4),
        value_feature="amount",
        fp_cost=15,
        segment=("region", ["North", "South", "East", "West"]),
        leak=("chargeback_filed", "Chargeback filed by cardholder (known 30-90 days later)"),
        future=("disputes_next_30d", "Disputes on this card in the following 30 days"),
    ),
    "banking_fraud": dict(
        title="Banking fraud (ATO, mules, circular transfers)",
        group="Fraud detection",
        target="is_fraud",
        base_rate=0.03,
        entity=("beneficiary_id", 150),
        ring=dict(size=6, effect=2.8, share=0.06),
        patterns=["Account takeover", "Mule accounts", "Circular transfers", "Synthetic identities"],
        features=[
            ("transfer_amount", "lognormal", 5.5, 1.0, 0.8, "USD", "Outgoing transfer amount"),
            ("new_beneficiary", "binary", 0.15, 0, 0.9, "flag", "Beneficiary added in last 24h"),
            ("login_anomaly", "uniform", 0, 1, 1.0, "score", "Login behaviour anomaly score"),
            ("password_reset_24h", "binary", 0.05, 0, 0.8, "flag", "Password reset in last 24h"),
            ("account_age_days", "lognormal", 6.5, 0.9, -0.6, "days", "Account age"),
            ("transfers_24h", "poisson", 2.0, 0, 0.6, "count", "Transfers in last 24h"),
            ("kyc_score", "uniform", 0, 1, -0.5, "score", "Identity verification strength"),
        ],
        interaction=("new_beneficiary", "login_anomaly", 1.5),
        value_feature="transfer_amount",
        fp_cost=60,
        segment=("channel", ["mobile", "web", "branch", "api"]),
        leak=("sar_filed", "Suspicious activity report filed (after investigation)"),
        future=("reversal_next_7d", "Transfer reversed within 7 days"),
    ),
    "insurance_fraud": dict(
        title="Insurance claims fraud",
        group="Fraud detection",
        target="is_fraud",
        base_rate=0.05,
        entity=("provider_id", 80),
        ring=dict(size=4, effect=2.4, share=0.06),
        patterns=["Duplicate claims", "Inflated claims", "Staged accidents", "Provider collusion"],
        features=[
            ("claim_amount", "lognormal", 8.0, 0.9, 0.9, "USD", "Claimed amount"),
            ("days_since_policy", "lognormal", 5.5, 1.0, -0.7, "days", "Days from policy start to claim"),
            ("prior_claims", "poisson", 0.6, 0, 0.7, "count", "Prior claims in 3 years"),
            ("witness", "binary", 0.4, 0, -0.5, "flag", "Independent witness present"),
            ("repair_shop_risk", "uniform", 0, 1, 0.8, "score", "Repair shop risk score"),
            ("injury_claimed", "binary", 0.3, 0, 0.5, "flag", "Injury claimed"),
        ],
        interaction=("claim_amount", "days_since_policy", -1.0),
        value_feature="claim_amount",
        fp_cost=400,
        loss_fraction=0.5,
        segment=("line", ["motor", "home", "travel", "health"]),
        leak=("siu_confirmed", "Special investigations unit outcome"),
        future=("claim_withdrawn_later", "Claim withdrawn after review"),
    ),
    "healthcare_fraud": dict(
        title="Healthcare billing fraud",
        group="Fraud detection",
        target="is_fraud",
        base_rate=0.04,
        entity=("provider_id", 90),
        ring=dict(size=5, effect=2.5, share=0.05),
        patterns=["Impossible procedures", "Excessive billing", "Phantom patients"],
        features=[
            ("billed_amount", "lognormal", 6.0, 0.9, 0.8, "USD", "Billed amount"),
            ("procedures_per_day", "poisson", 8.0, 0, 0.9, "count", "Provider procedures that day"),
            ("patient_age", "normal", 52, 18, -0.2, "years", "Patient age"),
            ("upcoding_score", "uniform", 0, 1, 1.0, "score", "Code-mix anomaly score"),
            ("distance_to_provider", "lognormal", 2.3, 0.9, 0.5, "km", "Patient distance to provider"),
            ("same_day_duplicates", "poisson", 0.2, 0, 0.8, "count", "Duplicate lines same day"),
        ],
        interaction=("procedures_per_day", "upcoding_score", 1.3),
        value_feature="billed_amount",
        fp_cost=120,
        segment=("specialty", ["cardiology", "orthopedics", "primary", "imaging"]),
        leak=("audit_recovery", "Amount recovered by post-payment audit"),
        future=("appeal_filed_later", "Provider appeal filed later"),
    ),
    "ecommerce_fraud": dict(
        title="E-commerce fraud (fake accounts, refund & promo abuse)",
        group="Fraud detection",
        target="is_fraud",
        base_rate=0.04,
        entity=("device_id", 200),
        ring=dict(size=8, effect=2.7, share=0.07),
        patterns=["Fake accounts", "Refund abuse", "Promo abuse", "Reseller networks"],
        features=[
            ("order_value", "lognormal", 4.0, 0.8, 0.6, "USD", "Order value"),
            ("account_age_days", "lognormal", 4.0, 1.4, -0.8, "days", "Account age"),
            ("promo_used", "binary", 0.25, 0, 0.6, "flag", "Promotion code used"),
            ("refunds_90d", "poisson", 0.4, 0, 0.9, "count", "Refunds in 90 days"),
            ("shipping_mismatch", "binary", 0.1, 0, 0.9, "flag", "Billing/shipping mismatch"),
            ("emails_per_device", "poisson", 1.2, 0, 0.8, "count", "Accounts sharing this device"),
        ],
        interaction=("promo_used", "emails_per_device", 1.4),
        value_feature="order_value",
        fp_cost=12,
        segment=("market", ["UK", "DE", "FR", "ES"]),
        leak=("refund_denied", "Refund denied by trust team"),
        future=("account_banned_later", "Account banned within 30 days"),
    ),
    "procurement_fraud": dict(
        title="Procurement fraud (collusion, split POs, duplicate invoices)",
        group="Fraud detection",
        target="is_fraud",
        base_rate=0.05,
        entity=("vendor_id", 60),
        ring=dict(size=4, effect=2.6, share=0.06),
        patterns=["Vendor collusion", "Split purchase orders", "Duplicate invoices", "Price inflation"],
        features=[
            ("invoice_amount", "lognormal", 8.5, 1.0, 0.7, "USD", "Invoice amount"),
            ("below_approval_limit", "binary", 0.2, 0, 0.9, "flag", "Just below approval threshold"),
            ("price_vs_benchmark", "normal", 1.0, 0.15, 1.0, "ratio", "Unit price vs benchmark"),
            ("duplicate_score", "uniform", 0, 1, 0.9, "score", "Similarity to earlier invoices"),
            ("vendor_age_days", "lognormal", 6.0, 1.0, -0.6, "days", "Vendor relationship age"),
            ("approver_changes", "poisson", 0.3, 0, 0.5, "count", "Approver changes on this PO"),
        ],
        interaction=("below_approval_limit", "duplicate_score", 1.2),
        value_feature="invoice_amount",
        fp_cost=600,
        loss_fraction=0.2,
        segment=("business_unit", ["ops", "it", "facilities", "marketing"]),
        leak=("audit_flag", "Internal audit finding"),
        future=("credit_note_later", "Credit note issued later"),
    ),
    "payroll_fraud": dict(
        title="Payroll fraud (ghost employees, shared bank accounts)",
        group="Fraud detection",
        target="is_fraud",
        base_rate=0.02,
        entity=("bank_account", 300),
        ring=dict(size=5, effect=3.0, share=0.04),
        patterns=["Ghost employees", "Duplicate bank accounts", "Unusual overtime"],
        features=[
            ("gross_pay", "lognormal", 8.2, 0.4, 0.4, "USD", "Monthly gross pay"),
            ("overtime_hours", "lognormal", 2.0, 0.9, 0.9, "hours", "Overtime hours"),
            ("badge_swipes", "poisson", 18, 0, -1.0, "count", "Building badge swipes"),
            ("shared_bank_account", "binary", 0.03, 0, 1.2, "flag", "Bank account shared with another employee"),
            ("manager_approvals", "poisson", 1.0, 0, -0.4, "count", "Timesheet approvals"),
            ("tenure_months", "lognormal", 3.0, 0.9, -0.3, "months", "Tenure"),
        ],
        interaction=("overtime_hours", "badge_swipes", -1.3),
        value_feature="gross_pay",
        fp_cost=500,
        loss_fraction=0.5,
        segment=("site", ["HQ", "Plant A", "Plant B", "Remote"]),
        leak=("hr_investigation_closed", "HR investigation outcome"),
        future=("employment_terminated_later", "Employment terminated later"),
    ),
    "telecom_fraud": dict(
        title="Telecom fraud (SIM abuse, subscription fraud, calling patterns)",
        group="Fraud detection",
        target="is_fraud",
        base_rate=0.03,
        entity=("imei_id", 250),
        ring=dict(size=6, effect=2.6, share=0.05),
        patterns=["SIM box abuse", "Subscription fraud", "Unusual calling patterns"],
        features=[
            ("intl_minutes", "lognormal", 2.5, 1.2, 0.9, "min", "International minutes"),
            ("calls_per_hour", "poisson", 3.0, 0, 1.0, "count", "Outgoing calls per hour"),
            ("distinct_numbers", "poisson", 8.0, 0, 0.8, "count", "Distinct numbers called"),
            ("sim_age_days", "lognormal", 5.0, 1.2, -0.7, "days", "SIM age"),
            ("roaming", "binary", 0.08, 0, 0.4, "flag", "Roaming"),
            ("prepaid", "binary", 0.45, 0, 0.3, "flag", "Prepaid plan"),
        ],
        interaction=("calls_per_hour", "distinct_numbers", 1.5),
        value_feature="intl_minutes",
        fp_cost=10,
        segment=("plan", ["prepaid", "postpaid", "business", "iot"]),
        leak=("fraud_desk_block", "Blocked by fraud desk"),
        future=("unpaid_bill_later", "Bill unpaid 60 days later"),
        avoid=["data_drift"],
    ),
    "adclick_fraud": dict(
        title="Ad-click fraud (bots, click farms, coordinated devices)",
        group="Fraud detection",
        target="is_fraud",
        base_rate=0.06,
        entity=("ip_block", 180),
        ring=dict(size=10, effect=2.4, share=0.08),
        patterns=["Bots", "Click farms", "Coordinated devices"],
        features=[
            ("clicks_per_min", "poisson", 1.5, 0, 1.1, "count", "Clicks per minute"),
            ("dwell_seconds", "lognormal", 3.0, 0.9, -1.0, "s", "Time on landing page"),
            ("mouse_entropy", "uniform", 0, 1, -0.9, "score", "Mouse movement entropy"),
            ("datacenter_ip", "binary", 0.08, 0, 1.1, "flag", "IP from a datacenter range"),
            ("conversion", "binary", 0.03, 0, -0.8, "flag", "Converted"),
            ("ua_rarity", "uniform", 0, 1, 0.6, "score", "User-agent rarity"),
        ],
        interaction=("clicks_per_min", "mouse_entropy", -1.2),
        value_feature=None,
        fn_cost=4,
        fp_cost=1,
        segment=("publisher", ["news", "games", "video", "shopping"]),
        leak=("advertiser_refund", "Advertiser refund issued"),
        future=("ip_blacklisted_later", "IP blacklisted later"),
    ),
    "gaming_fraud": dict(
        title="Gaming fraud (bots, item laundering, account farming)",
        group="Fraud detection",
        target="is_fraud",
        base_rate=0.04,
        entity=("guild_id", 70),
        ring=dict(size=5, effect=2.7, share=0.06),
        patterns=["Bots", "Virtual-item laundering", "Account farming", "Payment abuse"],
        features=[
            ("session_hours", "lognormal", 1.5, 0.8, 0.8, "h", "Session length"),
            ("actions_per_min", "normal", 40, 15, 0.9, "count", "Actions per minute"),
            ("gold_transfers", "poisson", 1.0, 0, 1.0, "count", "Gold transfers today"),
            ("account_age_days", "lognormal", 4.0, 1.3, -0.7, "days", "Account age"),
            ("purchase_amount", "lognormal", 2.5, 1.2, 0.5, "USD", "Real-money purchases"),
            ("chat_messages", "poisson", 20, 0, -0.6, "count", "Chat messages"),
        ],
        interaction=("session_hours", "actions_per_min", 1.3),
        value_feature="purchase_amount",
        fp_cost=8,
        segment=("region", ["NA", "EU", "APAC", "LATAM"]),
        leak=("gm_ban", "Game master ban decision"),
        future=("chargeback_later", "Payment chargeback later"),
        consumes=["fraud_wave"],
    ),
    "customer_churn": dict(
        title="Customer churn classification",
        group="Classification",
        target="churned",
        base_rate=0.12,
        entity=("account_manager", 30),
        features=[
            ("tenure_months", "lognormal", 3.0, 0.9, -0.9, "months", "Customer tenure"),
            ("support_tickets", "poisson", 1.5, 0, 0.8, "count", "Tickets in 90 days"),
            ("response_hours", "lognormal", 2.0, 0.8, 0.9, "h", "Average response time"),
            ("usage_trend", "normal", 0, 1, -1.0, "z", "Usage trend"),
            ("price_increase", "binary", 0.2, 0, 0.6, "flag", "Price increase at renewal"),
            ("nps", "normal", 30, 25, -0.7, "score", "Net promoter score"),
        ],
        interaction=("support_tickets", "response_hours", 1.2),
        value_feature=None,
        fn_cost=400,
        fp_cost=40,
        segment=("segment", ["SMB", "Mid-Market", "Enterprise", "Retail"]),
        leak=("cancellation_reason", "Cancellation reason captured at exit"),
        future=("downgrade_next_month", "Plan downgrade next month"),
    ),
    "predictive_maintenance": dict(
        title="Predictive maintenance (failure within 7 days)",
        group="IoT & maintenance",
        target="fails_7d",
        base_rate=0.05,
        entity=("machine_id", 40),
        features=[
            ("vibration_rms", "lognormal", 0.8, 0.4, 1.1, "mm/s", "Vibration RMS"),
            ("bearing_temp", "normal", 62, 6, 0.9, "°C", "Bearing temperature"),
            ("oil_debris", "poisson", 3, 0, 0.8, "count", "Oil debris particles"),
            ("load_pct", "uniform", 30, 100, 0.4, "%", "Load"),
            ("hours_since_service", "lognormal", 6.5, 0.6, 0.7, "h", "Hours since last service"),
            ("ambient_temp", "normal", 22, 6, 0.1, "°C", "Ambient temperature"),
        ],
        interaction=("vibration_rms", "bearing_temp", 1.3),
        value_feature=None,
        fn_cost=5000,
        fp_cost=300,
        segment=("failure_mode", ["bearing", "gearbox", "electrical", "hydraulic"]),
        leak=("work_order_created", "Corrective work order created"),
        future=("downtime_hours_next_week", "Downtime hours next week"),
    ),
    "iot_anomaly": dict(
        title="IoT sensor anomaly detection",
        group="IoT & maintenance",
        target="is_anomaly",
        base_rate=0.04,
        entity=("gateway_id", 20),
        features=[
            ("temperature", "normal", 60, 5, 1.0, "°C", "Process temperature"),
            ("pressure", "normal", 5.2, 0.4, -0.8, "bar", "Line pressure"),
            ("flow", "normal", 120, 15, -0.6, "l/min", "Flow rate"),
            ("current", "normal", 18, 2.5, 0.7, "A", "Motor current"),
            ("vibration", "lognormal", 0.7, 0.4, 0.9, "mm/s", "Vibration"),
            ("packet_delay_ms", "lognormal", 3.0, 0.6, 0.2, "ms", "Telemetry delay"),
        ],
        interaction=("temperature", "current", 1.2),
        value_feature=None,
        fn_cost=800,
        fp_cost=50,
        segment=("device", ["D-01", "D-02", "D-03", "D-07"]),
        leak=("operator_ack", "Operator acknowledged alarm"),
        future=("maintenance_next_day", "Maintenance logged next day"),
        drift_mode="segment",
        consumes=["sensor_faults"],
    ),
    "vision_defects": dict(
        title="Computer-vision defect detection (image features)",
        group="Vision",
        target="defect",
        base_rate=0.08,
        entity=("camera_id", 12),
        visual="surface",
        features=[
            ("brightness", "normal", 150, 8, 0.0, "px", "Mean image brightness"),
            ("contrast", "normal", 12, 2, 0.4, "px", "Image contrast"),
            ("edge_density", "lognormal", -4.0, 0.5, 0.9, "ratio", "Share of strong edges"),
            ("residual_peak", "lognormal", 2.8, 0.3, 1.2, "px", "Peak local residual"),
            ("blob_area", "lognormal", -5.0, 0.7, 1.1, "ratio", "Area of dark blobs"),
        ],
        interaction=("residual_peak", "blob_area", 1.2),
        value_feature=None,
        fn_cost=200,
        fp_cost=10,
        segment=("line", ["L1", "L2", "L3", "L4"]),
        leak=("rework_ticket", "Rework ticket opened at end of line"),
        future=("customer_return_later", "Customer return later"),
        drift_mode="segment",
    ),
    "rag_quality": dict(
        title="LLM/RAG answer-quality prediction",
        group="LLM & RAG",
        target="answer_wrong",
        base_rate=0.1,
        entity=("collection", 16),
        features=[
            ("retrieval_score", "uniform", 0.2, 1.0, -1.1, "cosine", "Top-1 retrieval similarity"),
            ("doc_age_days", "lognormal", 4.5, 0.8, 0.7, "days", "Age of top document"),
            ("context_tokens", "lognormal", 7.0, 0.4, 0.3, "tokens", "Context length"),
            ("citation_overlap", "uniform", 0, 1, -0.9, "ratio", "Answer/citation overlap"),
            ("query_ambiguity", "uniform", 0, 1, 0.8, "score", "Query ambiguity"),
        ],
        interaction=("retrieval_score", "doc_age_days", -1.0),
        value_feature=None,
        fn_cost=50,
        fp_cost=5,
        segment=("domain", ["policy", "product", "hr", "legal"]),
        leak=("human_rating", "Human reviewer rating"),
        future=("ticket_reopened_later", "Support ticket reopened later"),
    ),
    "recommendation_ctr": dict(
        title="Recommendation click prediction",
        group="Recommendation",
        target="clicked",
        base_rate=0.08,
        entity=("item_cluster", 50),
        features=[
            ("prior_exposure", "poisson", 3, 0, 0.9, "count", "Times shown before"),
            ("popularity", "lognormal", 2.0, 1.0, 0.8, "score", "Item popularity"),
            ("user_affinity", "uniform", 0, 1, 1.1, "score", "User-category affinity"),
            ("price", "lognormal", 3.0, 0.7, -0.5, "USD", "Item price"),
            ("freshness_days", "lognormal", 2.5, 1.0, -0.6, "days", "Days since item launch"),
        ],
        interaction=("user_affinity", "freshness_days", -1.1),
        value_feature=None,
        fn_cost=2,
        fp_cost=0.5,
        segment=("user_cohort", ["new", "casual", "loyal", "lapsed"]),
        leak=("purchase_after_click", "Purchase after the click"),
        future=("clicks_next_week", "Clicks next week"),
    ),
}

# Forecasting profiles: series, weekly shape, yearly amplitude, trend, driver, unit, noise.
WEEKLY = {
    "retail": [0.85, 0.8, 0.85, 0.95, 1.1, 1.35, 1.1],
    "workday": [1.15, 1.1, 1.1, 1.05, 1.0, 0.35, 0.3],
    "flat": [1.0, 1.0, 1.0, 1.0, 1.0, 0.95, 0.95],
    "weekend": [0.8, 0.8, 0.85, 0.9, 1.1, 1.3, 1.25],
}
FORECASTING = {
    "sales_forecast": dict(title="Sales forecasting", series=["North", "South", "East", "West"], level=(900, 1600), weekly="retail", yearly=0.18, trend=0.08, driver=("promo", 0.15, 0.6), unit="units", noise=0.08),
    "inventory_forecast": dict(title="Inventory demand forecasting", series=["DC-1", "DC-2", "DC-3", "DC-4"], level=(400, 900), weekly="retail", yearly=0.12, trend=0.05, driver=("promo", 0.12, 0.5), unit="units", noise=0.09, consumes=["stockouts", "delayed_shipments"]),
    "energy_demand": dict(title="Energy-demand forecasting", series=["Zone A", "Zone B", "Zone C", "Zone D"], level=(3000, 5000), weekly="workday", yearly=0.25, trend=0.02, driver=("cold_day", 0.2, 0.35), unit="MWh", noise=0.04, consumes=["weather_extreme", "power_loss"], avoid=["data_drift", "concept_drift"]),
    "hospital_volume": dict(title="Hospital patient-volume forecasting", series=["ED", "Outpatient", "Inpatient", "Maternity"], level=(120, 400), weekly="workday", yearly=0.2, trend=0.03, driver=("flu_index_high", 0.15, 0.3), unit="patients", noise=0.08, count=True, consumes=["hospital_surge"], avoid=["data_drift", "concept_drift"]),
    "callcenter_workload": dict(title="Call-center workload forecasting", series=["Billing", "Tech", "Sales", "Retention"], level=(600, 1400), weekly="workday", yearly=0.1, trend=0.04, driver=("campaign", 0.1, 0.45), unit="calls", noise=0.07, avoid=["data_drift", "concept_drift"]),
    "cloud_capacity": dict(title="Cloud-capacity forecasting", series=["api", "batch", "storage", "ml"], level=(2000, 6000), weekly="workday", yearly=0.05, trend=0.35, driver=("release_day", 0.08, 0.3), unit="vCPU-h", noise=0.05, consumes=["cloud_outage"]),
    "manufacturing_output": dict(title="Manufacturing production forecasting", series=["Line 1", "Line 2", "Line 3", "Line 4"], level=(800, 1200), weekly="workday", yearly=0.06, trend=0.02, driver=("extra_shift", 0.1, 0.25), unit="units", noise=0.05, consumes=["delayed_shipments"], avoid=["data_drift", "concept_drift"]),
    "spare_parts": dict(title="Spare-parts demand forecasting", series=["Bearings", "Seals", "Filters", "Pumps"], level=(20, 80), weekly="flat", yearly=0.1, trend=0.05, driver=("maintenance_campaign", 0.1, 0.8), unit="parts", noise=0.18, count=True, consumes=["equipment_defects"]),
    "traffic_forecast": dict(title="Traffic forecasting", series=["Ring road", "Bridge", "Tunnel", "Airport link"], level=(20000, 45000), weekly="workday", yearly=0.08, trend=0.02, driver=("event_day", 0.08, 0.35), unit="vehicles", noise=0.05, consumes=["road_closures"], avoid=["data_drift", "concept_drift"]),
    "hotel_airline_demand": dict(title="Hotel / airline demand forecasting", series=["LON", "PAR", "NYC", "SIN"], level=(300, 700), weekly="weekend", yearly=0.3, trend=0.06, driver=("conference", 0.07, 0.7), unit="bookings", noise=0.08),
    "cash_flow": dict(title="Cash-flow forecasting", series=["Receipts EU", "Receipts US", "Payables EU", "Payables US"], level=(80000, 150000), weekly="workday", yearly=0.1, trend=0.03, driver=("payroll_day", 0.07, 0.9), unit="USD", noise=0.1, consumes=["market_shock"]),
    "machine_failures": dict(title="Machine-failure forecasting", series=["Presses", "Pumps", "Conveyors", "Robots"], level=(4, 12), weekly="workday", yearly=0.05, trend=0.1, driver=("heatwave", 0.1, 0.6), unit="failures", noise=0.2, count=True, consumes=["sensor_faults"], avoid=["data_drift", "concept_drift"]),
}

FAILURES = {
    "data_drift": dict(label="Data drift", families=["classification", "forecasting"], fix="retrain_recent", explain="Production feature distributions moved away from the training data."),
    "concept_drift": dict(label="Concept drift", families=["classification", "forecasting"], fix="retrain_recent", explain="The relationship between features and target changed in production."),
    "label_leakage": dict(label="Label leakage", families=["classification"], fix="drop_feature", explain="A feature derived from the label made offline results look excellent."),
    "feature_leakage": dict(label="Feature leakage (future information)", families=["classification", "forecasting"], fix="drop_feature", explain="A feature used information from after the prediction time."),
    "wrong_labels": dict(label="Wrong labels", families=["classification", "forecasting"], fix="clean_labels", explain="Part of the training ground truth was corrupted."),
    "class_imbalance": dict(label="Class imbalance", families=["classification"], fix="rebalance", explain="Positives are so rare that the model predicts almost none."),
    "biased_sample": dict(label="Biased training sample", families=["classification", "forecasting"], fix="resample_representative", explain="Training data covered only part of the population."),
    "missing_feature": dict(label="Missing-feature failure", families=["classification", "forecasting"], fix="restore_feature", explain="An important feature stopped arriving and was silently filled."),
    "schema_change": dict(label="Schema change (units)", families=["classification", "forecasting"], fix="fix_units", explain="A field changed units in production."),
    "pipeline_bug": dict(label="Silent feature-pipeline bug", families=["classification", "forecasting"], fix="fix_pipeline", explain="Serving code mixed up features."),
    "overfitting": dict(label="Overfitting", families=["classification", "forecasting"], fix="regularize", explain="The model memorised noise in a small training set."),
    "underfitting": dict(label="Underfitting", families=["classification", "forecasting"], fix="increase_capacity", explain="The model is too simple for the relationship."),
    "bad_threshold": dict(label="Bad threshold selection", families=["classification"], fix="tune_threshold", explain="The decision threshold ignores business costs."),
    "poor_calibration": dict(label="Poor calibration", families=["classification"], fix="recalibrate", explain="Scores are not trustworthy probabilities."),
    "seasonality_failure": dict(label="Forecast seasonality failure", families=["forecasting"], fix="add_seasonality", explain="The model ignores weekly seasonality."),
    "holiday_event": dict(label="Unexpected holiday / event", families=["forecasting"], fix="add_event_feature", explain="Known calendar events were not modelled."),
    "cold_start": dict(label="Cold-start forecasting", families=["forecasting"], fix="pooled_fallback", explain="A new series has no history."),
    "delayed_labels": dict(label="Delayed labels", families=["classification", "forecasting"], fix="label_lag_eval", explain="Recent outcomes are not yet known; monitoring treats them as negatives."),
    "version_mismatch": dict(label="Model-version mismatch", families=["classification", "forecasting"], fix="redeploy_version", explain="Production serves a different model version than the one approved."),
    "stale_model": dict(label="Stale model", families=["classification", "forecasting"], fix="retrain_recent", explain="The model was trained long ago and the world moved on."),
    "training_serving_skew": dict(label="Training/serving skew", families=["classification", "forecasting"], fix="fix_pipeline", explain="A feature is computed differently at serving time."),
}
FIXES = {
    "retrain_recent": dict(label="Retrain on recent labelled production data", needs_feature=False),
    "drop_feature": dict(label="Remove a feature from the model", needs_feature=True),
    "clean_labels": dict(label="Relabel training data from the audit sample", needs_feature=False),
    "rebalance": dict(label="Rebalance classes and re-select the operating threshold", needs_feature=False),
    "resample_representative": dict(label="Retrain on a representative sample", needs_feature=False),
    "restore_feature": dict(label="Restore the missing feature feed", needs_feature=True),
    "fix_units": dict(label="Fix unit conversion for a feature", needs_feature=True),
    "fix_pipeline": dict(label="Fix serving pipeline for a feature", needs_feature=True),
    "regularize": dict(label="Regularize the model", needs_feature=False),
    "increase_capacity": dict(label="Use a more expressive model", needs_feature=False),
    "tune_threshold": dict(label="Tune threshold on business cost", needs_feature=False),
    "recalibrate": dict(label="Recalibrate scores (isotonic)", needs_feature=False),
    "add_seasonality": dict(label="Add day-of-week seasonality", needs_feature=False),
    "add_event_feature": dict(label="Add holiday/event calendar feature", needs_feature=False),
    "pooled_fallback": dict(label="Pooled cross-series fallback for new series", needs_feature=False),
    "label_lag_eval": dict(label="Evaluate only on matured labels", needs_feature=False),
    "redeploy_version": dict(label="Redeploy the approved model version", needs_feature=False),
}
# Failures that cannot be combined because they define the same part of the pipeline.
EXCLUSIVE = [
    {"overfitting", "underfitting"},
    {"stale_model", "version_mismatch"},
    {"stale_model", "overfitting"},
    {"class_imbalance", "overfitting"},
    {"seasonality_failure", "underfitting"},
    {"seasonality_failure", "pipeline_bug"},
    {"cold_start", "biased_sample"},
]

FAILURE_DRILLS = {
    "data_drift": "gaming_fraud",
    "concept_drift": "banking_fraud",
    "label_leakage": "insurance_fraud",
    "feature_leakage": "ecommerce_fraud",
    "wrong_labels": "healthcare_fraud",
    "class_imbalance": "credit_card_fraud",
    "biased_sample": "customer_churn",
    "missing_feature": "telecom_fraud",
    "schema_change": "procurement_fraud",
    "pipeline_bug": "payroll_fraud",
    "overfitting": "adclick_fraud",
    "underfitting": "gaming_fraud",
    "bad_threshold": "ecommerce_fraud",
    "poor_calibration": "customer_churn",
    "seasonality_failure": "sales_forecast",
    "holiday_event": "hotel_airline_demand",
    "cold_start": "spare_parts",
    "delayed_labels": "banking_fraud",
    "version_mismatch": "insurance_fraud",
    "stale_model": "energy_demand",
    "training_serving_skew": "telecom_fraud",
}
ADVANCED = {
    "model_a_vs_b": dict(title="Model A beats Model B offline but loses in production", profile="insurance_fraud", failures=["label_leakage"], story="Two candidate models were compared offline. Model A won by a wide margin and was deployed, but production losses rose."),
    "accuracy_vs_loss": dict(title="Accuracy remains high while business loss increases", profile="credit_card_fraud", failures=["class_imbalance", "bad_threshold"], story="The dashboard shows 99% accuracy while fraud losses climb every week."),
    "blocking_legit": dict(title="Fraud model starts blocking legitimate customers", profile="ecommerce_fraud", failures=["data_drift", "bad_threshold"], params=dict(threshold=0.02), story="Customer complaints about declined orders tripled after a new premium segment launched."),
    "one_region_wrong": dict(title="Forecast accurate overall but catastrophically wrong for one region", profile="sales_forecast", failures=["data_drift"], story="Overall WAPE looks fine; one region's stores keep running out of stock or over-ordering."),
    "pdm_misses_mode": dict(title="Predictive-maintenance model repeatedly misses one failure type", profile="predictive_maintenance", failures=["biased_sample", "class_imbalance"], story="Bearing failures are caught but hydraulic failures keep surprising the plant."),
    "feedback_loop": dict(title="Recommendation model causes feedback-loop bias", profile="recommendation_ctr", failures=["biased_sample"], story="The model was trained only on items it previously chose to show; new and niche items never get a chance."),
    "alert_storm": dict(title="Anomaly detector generates alert storms", profile="iot_anomaly", failures=["schema_change", "bad_threshold"], params=dict(threshold=0.005), story="After a firmware update, operators receive thousands of alarms per shift."),
    "rag_deteriorates": dict(title="LLM/RAG evaluation suddenly deteriorates", profile="rag_quality", failures=["training_serving_skew", "delayed_labels"], story="After an embedding-model upgrade the quality monitor turned red, but human ratings arrive slowly."),
    "cv_lighting": dict(title="Computer-vision defect detector fails under new lighting", profile="vision_defects", failures=["data_drift"], story="Line L4 got new LED lighting last week; escapes rose while the model still looks confident."),
    "iot_calibration": dict(title="Sensor model fails because one IoT device has calibration drift", profile="iot_anomaly", failures=["data_drift"], story="Only one device's alarms look wrong, yet the whole model is blamed."),
}


def family(profile_key):
    return "forecasting" if profile_key in FORECASTING else "classification"


def profile(profile_key):
    source = FORECASTING if profile_key in FORECASTING else CLASSIFICATION
    return dict(source[profile_key], key=profile_key, family=family(profile_key))


def scenarios():
    """Every playable lab challenge."""
    items = []
    for key, p in CLASSIFICATION.items():
        if p["group"] == "Fraud detection":
            items.append(dict(key=f"fraud:{key}", title=p["title"], group="Fraud detection", profile=key, failures="random", story=f"Patterns: {', '.join(p['patterns'])}. Two hidden production problems plus a collusion ring.", consumes=p.get("consumes", [])))
    for key, p in FORECASTING.items():
        items.append(dict(key=f"forecast:{key}", title=p["title"], group="Forecasting", profile=key, failures="random", story=f"Daily {p['unit']} for {', '.join(p['series'])}. Two hidden production problems.", consumes=p.get("consumes", [])))
    for failure, prof in FAILURE_DRILLS.items():
        items.append(dict(key=f"drill:{failure}", title=FAILURES[failure]["label"], group="Bad-prediction drills", profile=prof, failures=[failure], story=f"{FAILURES[failure]['explain']} Profile: {profile(prof)['title']}."))
    for key, a in ADVANCED.items():
        items.append(dict(key=f"advanced:{key}", title=a["title"], group="Advanced investigations", profile=a["profile"], failures=a["failures"], params=a.get("params", {}), story=a["story"]))
    for key, p in CLASSIFICATION.items():
        if p["group"] != "Fraud detection":
            items.append(dict(key=f"model:{key}", title=p["title"], group=p["group"], profile=key, failures="random", story="Random 1-3 hidden problems.", consumes=p.get("consumes", [])))
    return items
